{{ include "common.serviceaccount" . }}
---
{{ include "common.configmap" . }}
---
{{ include "common.secret" . }}
---
{{ include "common.deployment" . }}
---
{{ include "common.service" . }}
---
{{ include "common.hpa" . }}
---
{{ include "common.ingress" . }}
