global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8081']

  - job_name: 'resume-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['resume-service:8082']

  - job_name: 'interview-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['interview-service:8083']

  - job_name: 'feedback-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['feedback-service:8084']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']
